### PR TITLE
This is the html part of the footer.

### PR DESCRIPTION
**Pull request by erinepolley**
I have created the html part of the footer. I would like to add CSS elements later, such as putting the linked icons in a flexbox and having them inline to the left. But for now, this is the html stuff. 

git fetch -all
git checkout epfooter

### CODE REVIEW

**Comment by erinepolley** [comment]
git fetch -all
git checkout epfooter

**Comment by stitchelle** [comment]
would it be better to put the "back top of page" before the Social Media links?

**Review by josephwalker504 — DISMISSED** [review]
footer looks amazing

**Review by stitchelle — DISMISSED** [review]
looks good

**Review by Garcia-Julz — DISMISSED** [review]
good

**Comment by erinepolley** [comment]
Here is the new webpage with the nav bar added.

**Review by stitchelle — APPROVED** [review]
looks good

**Review by Garcia-Julz — APPROVED** [review]

**Pull request merged**
