### PR TITLE
added information into personal html

### PR DESCRIPTION
**Pull request by stitchelle**
1. ```git fetch --all```
2. ```git checkout mj_personal```
3. verify information and tags added to personal html

### CODE REVIEW

**Comment by erinepolley** [comment]
I checked the tags, classes, and content, and I think the webpage looks good. Did not find any typos.

**Review by erinepolley — APPROVED** [review]
I checked the tags, classes, and content, and I think the webpage looks good. Did not find any typos.

**Comment by Garcia-Julz** [comment]
HTML Looks good

**Comment by Garcia-Julz** [comment]
looksfine

**Review by Garcia-Julz — APPROVED** [review]
Looks good :D

**Pull request merged**
