### PR TITLE
Epnewsfeed

### PR DESCRIPTION
**Pull request by erinepolley**
```git fetch -all
git checkout epnewsfeed```

Finished newsfeed.html page. Please look over.

### CODE REVIEW

**Comment by stitchelle** [comment]
-Move class into `````` and remove ```<p>```
-change ```<p>``` on dates to ```<h4>``` or ```<h5>```

**Review by josephwalker504 — COMMENTED** [review]
looks good to me

**Review by stitchelle — APPROVED** [review]
looks good

**Comment by josephwalker504** [comment]
not really sure what I' doing

**Review by Garcia-Julz — APPROVED** [review]
looks fine

**Review by josephwalker504 — APPROVED** [review]

**Pull request merged**
