### PR TITLE
Created work files DustyDivots

### PR DESCRIPTION
**Pull request by josephwalker504**
git fetch --all
git checkout jwDustyDivot

verify Main, Executive, Career, Personal and NewsFeed files are present with Index. HTMlL and CSS in jwDustyDivot folder

### CODE REVIEW

**Comment by erinepolley** [comment]
The folders look great! Maybe just one suggestion: maybe keep the name of index.html the same on the executive file, but change the other names of the html files in the other folder? Thanks!

**Comment by Garcia-Julz** [comment]
Rename

**Comment by josephwalker504** [comment]
changes has been made on project

**Review by Garcia-Julz — APPROVED** [review]
Lookin good

**Review by stitchelle — APPROVED** [review]
Looks good

**Pull request merged**
