### PR TITLE
Jwcareer

### PR DESCRIPTION
**Pull request by josephwalker504**
git fetch --all 
git checkout jwcareer
look over code for correction and errors

### CODE REVIEW

**Comment by erinepolley** [comment]
The page looks good to me. The only thing is the extra bullet point on the "known collaborators" list. Just make sure to delete it if you decide not to put anything there. Thanks!

**Review by stitchelle — DISMISSED** [review]
Looks good

**Review by erinepolley — APPROVED** [review]
Perfecto.

**Review by stitchelle — APPROVED** [review]
Looks good

**Pull request merged**
